# Generated by Django 4.0.3 on 2022-04-12 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerengine', '0003_membership_price_membership_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='req',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='value',
            name='crypto',
        ),
        migrations.AddField(
            model_name='value',
            name='crypto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dealerengine.crypto'),
        ),
    ]
