# Generated by Django 4.0.3 on 2022-04-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealerengine', '0004_membership_req_remove_value_crypto_value_crypto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='req',
        ),
    ]
