# Generated by Django 4.0.3 on 2022-04-12 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerengine', '0005_remove_membership_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='member',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='dealerengine.membership'),
        ),
    ]
