# Generated by Django 4.0.3 on 2022-04-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerengine', '0006_alter_users_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='dealerengine.membership'),
        ),
    ]
