# Generated by Django 4.0.4 on 2022-04-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerengine', '0008_alter_value_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_exchange', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.CharField(max_length=32)),
            ],
        ),
    ]
