# Generated by Django 4.0.4 on 2022-04-16 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealerengine', '0009_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='account',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
