# Generated by Django 4.0.4 on 2022-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerengine', '0010_history_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='name_crypto',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='history',
            name='value_crypto',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='history',
            name='value_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
