# Generated by Django 4.0.3 on 2022-04-24 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerengine', '0014_alter_membership_price_alter_users_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cryptocurrency',
            field=models.ManyToManyField(through='dealerengine.Value', to='dealerengine.crypto'),
        ),
        migrations.AlterField(
            model_name='value',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealerengine.users'),
        ),
    ]
